---
name: 10 - Managing execution flow

on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        type: boolean
        description: Whether unit tests will pass or not
        default: true

jobs:
  # The `lint-build` job runs first, as it has no dependencies.
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and build
        run: echo "Linting and building project"

  # The `unit-tests` job also runs at the start, in parallel with `lint-build`.
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Running unit tests
        run: echo "Running tests..."
      # This step will only run if the `pass-unit-tests` input is `false`.
      - name: Failing tests
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1

  # The `deploy-nonprod` job will only start after both `lint-build` and `unit-tests` have completed successfully.
  deploy-nonprod:
    runs-on: ubuntu-latest
    # `needs` specifies the jobs that must complete successfully before this job will run.
    needs:
      - lint-build
      - unit-tests
    steps:
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod..."

  # The `e2e-tests` job depends on the successful completion of `deploy-nonprod`.
  # It will run in parallel with `load-tests`.
  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: Running E2E tests
        run: echo "Running E2E tests"

  # The `load-tests` job also depends on the successful completion of `deploy-nonprod`.
  # It will run in parallel with `e2e-tests`.
  load-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: Running load tests
        run: echo "Running load tests"

  # The `deploy-prod` job is the final job in this workflow.
  # It will only run after both `e2e-tests` and `load-tests` have completed successfully.
  deploy-prod:
    runs-on: ubuntu-latest
    needs:
      - e2e-tests
      - load-tests
    steps:
      - name: Deploying to prod
        run: echo "Deploying to prod..."
