name: 15 - Working with Matrices

on:
  workflow_dispatch:

jobs:
  backwards-compatibility:
    name: ${{ matrix.os }}-${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 23.x]
        os:
          - ubuntu-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            node-verion: 16.x
          - os: ubuntu-latest
            node-version: 23.x
            tag: experimental
    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 1
      - name: Performing some tests
        run: |
          echo "Running test on OS ${{ matrix.os }} & Node-version ${{ matrix.node-version }}"
          sleep 10
      - name: Upload test file
        run: echo "Uploading test file..."
