name: 16 - Working with environments
# run-name: 16 - environments workflow | env - ${{ inputs.target-env }}

on:
  workflow_dispatch:
    # inputs:
    #   target-env:
    #     type: environment

jobs:
  echo-non-prod:
    runs-on: ubuntu-latest
    environment: non-prod
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{ env.my-env-value }}"

  echo-prod:
    runs-on: ubuntu-latest
    needs: echo-non-prod
    environment: prod
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    steps:
      - name: Echo vars
        run: |
          echo "Env variable: ${{ env.my-env-value }}"
